server:
  port: 8083
  servlet:
    context-path: /ui
security:
  oauth2:
    client:
      clientId: userservice3
      clientSecret: 1234
      accessTokenUri: http://oauth2-server:8080/oauth/token
      userAuthorizationUri: http://oauth2-server:8080/oauth/authorize
      scope: FOO
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnBlEWUumxm8GiSNNaTyQ
          xfYv0tMkVx4gfxph4ueUuykHkZOt9TxhbkdYbw5ftwd9lWOcAEHmTXsCn+ekYVLz
          e06cJ8WsN06rZuLQEUVOQ40xlGmwGb4l5KEWv5w4o806dEex1tlNShgWeynYgsmp
          ri9M6WDY3FQFxHzdRriFFIlHe2ak9x3Js//BgcSXDxkQ6IDgqS3cNXVuf9dIu1yB
          mcIqLzejWkfZhboQ/HGGM1ByYPRf443Ny8Pn206VAfkJPIF1rdWYfaixqHpfviyX
          BNQInSNnad8NDkVjELo4Sp1L8m+rpuwPCv9n0Bvyf1Rw+X69Q/6uQYlznNSs5/78
          lwIDAQAB
          -----END PUBLIC KEY-----
spring:
  thymeleaf:
    cache: false

#logging:
#  level:
#    ROOT: DEBUG